name: django 
on: push 
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout the Code
      uses: actions/checkout@v3
    - name: Install requirements
      run: pip3 install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 webapp/*.py
        pylint --disable=C0301 --disable=C0326 webapp/*.py
    - name: Run unit tests
      run: |
        python3 -m unittest --verbose --failfast
