name: djangoapp-pipeline
on: push 
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout the Code
      uses: actions/checkout@v3
    - name: Install requirements
      run: pip3 install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 webapp/*.py
        pylint --exit-zero --disable=C0301 --disable=C0326 webapp/*.py
    - name: Run unit tests
      run: |
        python3 -m unittest --verbose --failfast
    - name: Sort imports
      run: |
        # stop the build if there are Python syntax errors or undefined names
        isort .
        isort --check --diff .
  build:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vishal267/djangoapp:latest
